### ISSUE TITLE
Use 'counter' as resource observed in observe sample

### ISSUE THREAD

**Issue by vancefarren** [golioth/zephyr-sdk#117]
Its confusing to subscribe to the 'observed' resource.  The other samples query 'counter' which is intuitive as a resource.  We should consider changing 'observed' to 'counter'

https://github.com/golioth/zephyr-sdk/blob/409ff7b4e6d4d8649e665cbe4e165ad2284ba464/samples/lightdb/observe/src/main.c#L71

**Comment by mniestroj** [comment]
Solved by #163
