### ISSUE TITLE
Use project groups to reduce extraneous modules for faster Zephyr setup

### ISSUE THREAD

**Issue by beriberikix** [golioth/zephyr-sdk#31]
https://github.com/zephyrproject-rtos/zephyr/pull/36981

We should identify what is not needed from a typical Golioth application. We may add more groups over time. Note that the user can always manually include a group through flags or their own west.yaml.

**Comment by vitprajzler** [comment]
@beriberikix - this is an older issue, is this still relevant to track? I'd open a new issue in case we need further improvements on the `west update` performance

**Comment by beriberikix** [comment]
Nope, Marcin addressed this already.
