### ISSUE TITLE
Start using Zephyr from tip of master

### ISSUE THREAD

**Issue by beriberikix** [golioth/zephyr-sdk#36]
Per https://github.com/golioth/zephyr/issues/31#issuecomment-887564702, "we need to start using Zephyr from tip of master (right now we still rely on stable 2.6.0)."

**Comment by 0Grit** [comment]
We periodically re-sync to the tip of main.

https://github.com/golioth/zephyr-sdk/pull/131
https://github.com/golioth/zephyr-sdk/pull/66
