### ISSUE TITLE
Eliminate net directory

### ISSUE THREAD

**Issue by 0Grit** [golioth/zephyr-sdk#85]
Extra layer of file structure can cause confusion

**Comment by 0Grit** [comment]
Maybe I'm giving attributing too much self importance to us but our service clients will end up interacting with a lot of zephyr and application subsystems outside just `networking`.

Lets eliminate the prefix.

Can you think of a way for this NOT to be a breaking change?

**Comment by vitprajzler** [comment]
I agree that in the long term, our SDK is going to be not just about networking. I don't think this is super important though, especially if it results in breaking changes for existing users.

**Comment by vitprajzler** [comment]
I don't consider this important right now, `net` is an ok location for the foreseeable future.
