### ISSUE TITLE
Basic commented description of SYS_INIT Macro in system_client.c

### ISSUE THREAD

**Issue by 0Grit** [golioth/zephyr-sdk#90]
Comment our usage of the SYS_INIT macro as this could be highly confusing to users unfamiliar with the complexity of this macro

https://github.com/golioth/zephyr-sdk/blob/ff39bf1c51e8185964c7de8b253ca4d657393ca8/net/golioth/system_client.c#L185-L186

Possibly move the macro into a more intuitive location as well?

**Comment by vitprajzler** [comment]
Mike, do you think this is something you could look into and see how much we can help our users with the usage of the macro? I don't know enough to judge the priority on this, so please work with Marcin.

**Comment by mniestroj** [comment]
`SYS_INIT()` is a standard Zephyr macro. Either `grep` or https://docs.zephyrproject.org/ can be used to figure out what it does.
